
package com.wumart.sap1.meipi.createso;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ZWEBSERVICE_MEIPI_CREATESO", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "file:/home/work/lsh-ofc/wumart/wsdl/1/ZWS_MEIPI_CREATESO.wsdl")
public class ZWEBSERVICEMEIPICREATESO
    extends Service
{

    private final static URL ZWEBSERVICEMEIPICREATESO_WSDL_LOCATION;
    private final static WebServiceException ZWEBSERVICEMEIPICREATESO_EXCEPTION;
    private final static QName ZWEBSERVICEMEIPICREATESO_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZWEBSERVICE_MEIPI_CREATESO");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/work/lsh-ofc/wumart/wsdl/1/ZWS_MEIPI_CREATESO.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZWEBSERVICEMEIPICREATESO_WSDL_LOCATION = url;
        ZWEBSERVICEMEIPICREATESO_EXCEPTION = e;
    }

    public ZWEBSERVICEMEIPICREATESO() {
        super(__getWsdlLocation(), ZWEBSERVICEMEIPICREATESO_QNAME);
    }

    public ZWEBSERVICEMEIPICREATESO(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZWEBSERVICEMEIPICREATESO_QNAME, features);
    }

    public ZWEBSERVICEMEIPICREATESO(URL wsdlLocation) {
        super(wsdlLocation, ZWEBSERVICEMEIPICREATESO_QNAME);
    }

    public ZWEBSERVICEMEIPICREATESO(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZWEBSERVICEMEIPICREATESO_QNAME, features);
    }

    public ZWEBSERVICEMEIPICREATESO(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZWEBSERVICEMEIPICREATESO(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZWSMEIPICREATESO
     */
    @WebEndpoint(name = "binding")
    public ZWSMEIPICREATESO getBinding() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "binding"), ZWSMEIPICREATESO.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZWSMEIPICREATESO
     */
    @WebEndpoint(name = "binding")
    public ZWSMEIPICREATESO getBinding(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "binding"), ZWSMEIPICREATESO.class, features);
    }

    /**
     * 
     * @return
     *     returns ZWSMEIPICREATESO
     */
    @WebEndpoint(name = "binding_SOAP12")
    public ZWSMEIPICREATESO getBindingSOAP12() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "binding_SOAP12"), ZWSMEIPICREATESO.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZWSMEIPICREATESO
     */
    @WebEndpoint(name = "binding_SOAP12")
    public ZWSMEIPICREATESO getBindingSOAP12(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "binding_SOAP12"), ZWSMEIPICREATESO.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZWEBSERVICEMEIPICREATESO_EXCEPTION!= null) {
            throw ZWEBSERVICEMEIPICREATESO_EXCEPTION;
        }
        return ZWEBSERVICEMEIPICREATESO_WSDL_LOCATION;
    }

}
