
package com.wumart.sap1.meipi.createso;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ZWS_MEIPI_CREATESO", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZWSMEIPICREATESO {


    /**
     * 
     * @param soitem
     * @param sopartners
     * @param soheader
     * @param _return
     * @return
     *     returns com.wumart.sap1.meipi.createso.TableOfBapiret2
     */
    @WebMethod(operationName = "ZBapiMeipiCreateso")
    @WebResult(name = "Return", targetNamespace = "")
    @RequestWrapper(localName = "ZBapiMeipiCreateso", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.wumart.sap1.meipi.createso.ZBapiMeipiCreateso")
    @ResponseWrapper(localName = "ZBapiMeipiCreatesoResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.wumart.sap1.meipi.createso.ZBapiMeipiCreatesoResponse")
    public TableOfBapiret2 zBapiMeipiCreateso(
        @WebParam(name = "Return", targetNamespace = "")
        TableOfBapiret2 _return,
        @WebParam(name = "Soheader", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<TableOfZbapiR2Createsohead> soheader,
        @WebParam(name = "Soitem", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<TableOfZbapiR2Createsoitem> soitem,
        @WebParam(name = "Sopartners", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<TableOfZbapiR2Createsopart> sopartners);

}
