
package com.wumart.sap1.obdstatus.select;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ZMP_OBDSTATUS_SELECT", targetNamespace = "urn:sap-com:document:sap:rfc:functions", wsdlLocation = "file:/home/work/lsh-ofc/wumart/wsdl/1/ZMP_OBDSTATUS_SELECT.wsdl")
public class ZMPOBDSTATUSSELECT_Service
    extends Service
{

    private final static URL ZMPOBDSTATUSSELECT_WSDL_LOCATION;
    private final static WebServiceException ZMPOBDSTATUSSELECT_EXCEPTION;
    private final static QName ZMPOBDSTATUSSELECT_QNAME = new QName("urn:sap-com:document:sap:rfc:functions", "ZMP_OBDSTATUS_SELECT");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/work/lsh-ofc/wumart/wsdl/1/ZMP_OBDSTATUS_SELECT.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZMPOBDSTATUSSELECT_WSDL_LOCATION = url;
        ZMPOBDSTATUSSELECT_EXCEPTION = e;
    }

    public ZMPOBDSTATUSSELECT_Service() {
        super(__getWsdlLocation(), ZMPOBDSTATUSSELECT_QNAME);
    }

    public ZMPOBDSTATUSSELECT_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZMPOBDSTATUSSELECT_QNAME, features);
    }

    public ZMPOBDSTATUSSELECT_Service(URL wsdlLocation) {
        super(wsdlLocation, ZMPOBDSTATUSSELECT_QNAME);
    }

    public ZMPOBDSTATUSSELECT_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZMPOBDSTATUSSELECT_QNAME, features);
    }

    public ZMPOBDSTATUSSELECT_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZMPOBDSTATUSSELECT_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZMPOBDSTATUSSELECT
     */
    @WebEndpoint(name = "binding")
    public ZMPOBDSTATUSSELECT getBinding() {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "binding"), ZMPOBDSTATUSSELECT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZMPOBDSTATUSSELECT
     */
    @WebEndpoint(name = "binding")
    public ZMPOBDSTATUSSELECT getBinding(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "binding"), ZMPOBDSTATUSSELECT.class, features);
    }

    /**
     * 
     * @return
     *     returns ZMPOBDSTATUSSELECT
     */
    @WebEndpoint(name = "binding_SOAP12")
    public ZMPOBDSTATUSSELECT getBindingSOAP12() {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "binding_SOAP12"), ZMPOBDSTATUSSELECT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZMPOBDSTATUSSELECT
     */
    @WebEndpoint(name = "binding_SOAP12")
    public ZMPOBDSTATUSSELECT getBindingSOAP12(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "binding_SOAP12"), ZMPOBDSTATUSSELECT.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZMPOBDSTATUSSELECT_EXCEPTION!= null) {
            throw ZMPOBDSTATUSSELECT_EXCEPTION;
        }
        return ZMPOBDSTATUSSELECT_WSDL_LOCATION;
    }

}
