
package com.lsh123.meipi.ofc.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OFCWebService", targetNamespace = "http://webservice.ofc.meipi.lsh123.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OFCWebService {


    /**
     * 
     * @param items
     * @param head
     * @return
     *     returns com.lsh123.meipi.ofc.webservice.CallRet
     */
    @WebMethod
    @WebResult(name = "ret", targetNamespace = "")
    @RequestWrapper(localName = "putOutboundOrder", targetNamespace = "http://webservice.ofc.meipi.lsh123.com/", className = "com.lsh123.meipi.ofc.webservice.PutOutboundOrder")
    @ResponseWrapper(localName = "putOutboundOrderResponse", targetNamespace = "http://webservice.ofc.meipi.lsh123.com/", className = "com.lsh123.meipi.ofc.webservice.PutOutboundOrderResponse")
    @Action(input = "http://webservice.ofc.meipi.lsh123.com/OFCWebService/putOutboundOrderRequest", output = "http://webservice.ofc.meipi.lsh123.com/OFCWebService/putOutboundOrderResponse")
    public CallRet putOutboundOrder(
        @WebParam(name = "head", targetNamespace = "")
        OutboundOrderHead head,
        @WebParam(name = "items", targetNamespace = "")
        List<OutboundOrderItem> items);

}
