
package com.lsh123.meipi.ofc.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OFCWebServiceService", targetNamespace = "http://webservice.ofc.meipi.lsh123.com/", wsdlLocation = "http://127.0.0.1:8081/webservice/wsdl/wumart/so/push?wsdl")
public class OFCWebServiceService
    extends Service
{

    private final static URL OFCWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException OFCWEBSERVICESERVICE_EXCEPTION;
    private final static QName OFCWEBSERVICESERVICE_QNAME = new QName("http://webservice.ofc.meipi.lsh123.com/", "OFCWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8081/webservice/wsdl/wumart/so/push?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OFCWEBSERVICESERVICE_WSDL_LOCATION = url;
        OFCWEBSERVICESERVICE_EXCEPTION = e;
    }

    public OFCWebServiceService() {
        super(__getWsdlLocation(), OFCWEBSERVICESERVICE_QNAME);
    }

    public OFCWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), OFCWEBSERVICESERVICE_QNAME, features);
    }

    public OFCWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, OFCWEBSERVICESERVICE_QNAME);
    }

    public OFCWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OFCWEBSERVICESERVICE_QNAME, features);
    }

    public OFCWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OFCWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OFCWebService
     */
    @WebEndpoint(name = "OFCWebServicePort")
    public OFCWebService getOFCWebServicePort() {
        return super.getPort(new QName("http://webservice.ofc.meipi.lsh123.com/", "OFCWebServicePort"), OFCWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OFCWebService
     */
    @WebEndpoint(name = "OFCWebServicePort")
    public OFCWebService getOFCWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.ofc.meipi.lsh123.com/", "OFCWebServicePort"), OFCWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OFCWEBSERVICESERVICE_EXCEPTION!= null) {
            throw OFCWEBSERVICESERVICE_EXCEPTION;
        }
        return OFCWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
