
package com.wumart.sap2.meipi.cus.maintain;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ZWEBSERVICE_MEIPI_CUS_N", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "file:/home/work/lsh-ofc/wumart/wsdl/2/ZWS_MEIPI_CUS_MAINTAIN_N.wsdl")
public class ZWEBSERVICEMEIPICUSN
    extends Service
{

    private final static URL ZWEBSERVICEMEIPICUSN_WSDL_LOCATION;
    private final static WebServiceException ZWEBSERVICEMEIPICUSN_EXCEPTION;
    private final static QName ZWEBSERVICEMEIPICUSN_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZWEBSERVICE_MEIPI_CUS_N");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/work/lsh-ofc/wumart/wsdl/2/ZWS_MEIPI_CUS_MAINTAIN_N.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZWEBSERVICEMEIPICUSN_WSDL_LOCATION = url;
        ZWEBSERVICEMEIPICUSN_EXCEPTION = e;
    }

    public ZWEBSERVICEMEIPICUSN() {
        super(__getWsdlLocation(), ZWEBSERVICEMEIPICUSN_QNAME);
    }

    public ZWEBSERVICEMEIPICUSN(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZWEBSERVICEMEIPICUSN_QNAME, features);
    }

    public ZWEBSERVICEMEIPICUSN(URL wsdlLocation) {
        super(wsdlLocation, ZWEBSERVICEMEIPICUSN_QNAME);
    }

    public ZWEBSERVICEMEIPICUSN(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZWEBSERVICEMEIPICUSN_QNAME, features);
    }

    public ZWEBSERVICEMEIPICUSN(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZWEBSERVICEMEIPICUSN(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZWSMEIPICUSMAINTAINN
     */
    @WebEndpoint(name = "binding")
    public ZWSMEIPICUSMAINTAINN getBinding() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "binding"), ZWSMEIPICUSMAINTAINN.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZWSMEIPICUSMAINTAINN
     */
    @WebEndpoint(name = "binding")
    public ZWSMEIPICUSMAINTAINN getBinding(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "binding"), ZWSMEIPICUSMAINTAINN.class, features);
    }

    /**
     * 
     * @return
     *     returns ZWSMEIPICUSMAINTAINN
     */
    @WebEndpoint(name = "binding_SOAP12")
    public ZWSMEIPICUSMAINTAINN getBindingSOAP12() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "binding_SOAP12"), ZWSMEIPICUSMAINTAINN.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZWSMEIPICUSMAINTAINN
     */
    @WebEndpoint(name = "binding_SOAP12")
    public ZWSMEIPICUSMAINTAINN getBindingSOAP12(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "binding_SOAP12"), ZWSMEIPICUSMAINTAINN.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZWEBSERVICEMEIPICUSN_EXCEPTION!= null) {
            throw ZWEBSERVICEMEIPICUSN_EXCEPTION;
        }
        return ZWEBSERVICEMEIPICUSN_WSDL_LOCATION;
    }

}
